baseURL = 'https://kittenlover.dev/'
languageCode = 'en-us'
title = "Kittenlover's Rooftop"
enableGitInfo = true
enableRobotsTXT = true
rssLimit = 20

[minify]
  disableCSS = false
  minifyOutput = true

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    hl_Lines = ''
    hl_inline = false
    lineNoStart = 1
    noClasses = true
    style = 'algol_nu'
    tabWidth = 2
[mediaTypes]
  [mediaTypes."text/bibtex"]
    suffixes = ["bib"]
[outputFormats]
  [outputFormats.Bibcite]
    baseName = ''
    isPlainText = true
    mediaType = 'text/bibtex'
    permalinkable = true

[outputs]
  page = ['HTML', 'BIBCITE']
